# Generated by Django 5.2.7 on 2025-10-24 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatepass', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepass',
            name='actual_return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='actual_return_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='return_notes',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='return_verified_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'security'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_verifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('warden_approved', 'Warden Approved'), ('warden_rejected', 'Warden Rejected'), ('security_approved', 'Security Approved'), ('returned', 'Returned'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
