# Generated by Django 5.2.7 on 2025-10-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatepass', '0002_gatepass_actual_return_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='shift',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Night', 'Night')], default='Morning', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
